### ISSUE TITLE
Unable to quickstart the project

### ISSUE THREAD

**Issue by thirubala** [ravivaniya4911/hello-flask-react#1]
When I try the command hasura quickstart hello-flask-react I get the error that 

**Quickstart failed! error=[1005] Project 'hello-flask-react' not found on Hasura Hub (https://hasura.io/hub)**

**Comment by ravivaniya4911** [comment]
Hey thirubala do
$ hasura quickstart ravi/hello-flask-react 
if a problem doesn't get solved then please raise an issue
